@template.layout.index(content = @`
    <div class="container">
        <div class="card shadow-sm mb-4">
            <div class="card-body">
                <h2 class="card-title mb-2">
                    Access Denied - You are not authorized to access this resource.
                </h2>

                <a href="/dashboard">Back to Dashboard Page</a>
            </div>
        </div>
    </div>
`)